from __future__ import annotations

from ai_rules.models import EffectiveRules, RuleSeverity

_ORDER = (
    RuleSeverity.REQUIRED,
    RuleSeverity.USER_DECISION,
    RuleSeverity.PREFERRED,
    RuleSeverity.CONDITIONAL,
    RuleSeverity.OPTIONAL,
)


def render_generated_rules(effective: EffectiveRules, rules_version: str) -> str:
    lines = [
        "# AI Engineering Rules",
        f"Generated by airules {rules_version}",
        "",
        "This file is generated. Edit `.ai-rules/project.md` for project-specific instructions.",
        "Project-specific instructions and explicit user requests override generic preferences.",
        "",
    ]
    for severity in _ORDER:
        group = [rule for rule in effective.rules if rule.severity is severity]
        if not group:
            continue
        lines.extend([f"## {severity.name}", ""])
        for rule in group:
            source = effective.sources.get(rule.id, "unknown")
            lines.append(f"<!-- source: {source}; rule: {rule.id} -->")
            lines.append(rule.body.rstrip())
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"
