import pytest

from ai_rules.adapters.claude import render_claude
from ai_rules.adapters.codex import render_codex
from ai_rules.adapters.cursor import render_cursor
from ai_rules.adapters.gemini import render_gemini
from ai_rules.errors import ConfigurationError


def test_text_adapters_preserve_user_content() -> None:
    existing = "# User instructions\nKeep this.\n"
    for render in (render_codex, render_claude, render_gemini):
        result = render(existing)
        assert "# User instructions\nKeep this.\n" in result
        assert result.count("<!-- ai-engineering-rules:start -->") == 1


def test_cursor_adapter_is_owned_and_rejects_foreign_existing_file() -> None:
    rendered = render_cursor(None)
    assert "Shared engineering rules generated by airules" in rendered
    assert "@../../.ai-rules/generated.md" in rendered
    assert "ai-engineering-rules:owned" in rendered

    with pytest.raises(ConfigurationError, match="not owned"):
        render_cursor("user managed cursor rule\n")


def test_cursor_adapter_can_refresh_owned_file() -> None:
    first = render_cursor(None)
    assert render_cursor(first) == first
