from __future__ import annotations

from ai_rules.adapters.native import group_effective_rules, render_group_markdown
from ai_rules.errors import ConfigurationError
from ai_rules.models import EffectiveRules

OWNER = "<!-- ai-engineering-rules:owned -->"
LEGACY_FILENAME = "engineering.mdc"


def _owned_mdc(description: str, body: str) -> str:
    return (
        "---\n"
        f"description: {description}\n"
        "globs:\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"{OWNER}\n\n"
        f"{body.rstrip()}\n"
    )


def render_cursor_native(effective: EffectiveRules, project_text: str) -> dict[str, str]:
    rendered: dict[str, str] = {}
    for group in group_effective_rules(effective):
        rendered[f"airules-{group.key}.mdc"] = _owned_mdc(
            f"airules {group.title} engineering rules",
            render_group_markdown(group, effective),
        )
    rendered["airules-999-project.mdc"] = _owned_mdc(
        "Project-specific instructions managed through .ai-rules/project.md",
        project_text,
    )
    return rendered


def is_owned_cursor_rule(content: str | None) -> bool:
    return content is not None and OWNER in content


# Compatibility helper for recognizing/refreshing the pre-0.3 owned adapter.
def render_cursor(existing: str | None) -> str:
    content = _owned_mdc(
        "Shared engineering rules generated by airules",
        "@../../.ai-rules/generated.md\n@../../.ai-rules/project.md",
    )
    if existing is not None and OWNER not in existing:
        raise ConfigurationError("Cursor engineering.mdc exists but is not owned by airules")
    return content
