from __future__ import annotations

from ai_rules.errors import ConfigurationError

_OWNER = "<!-- ai-engineering-rules:owned -->"
_CONTENT = f"""{_OWNER}
---
description: Shared engineering rules generated by airules
globs:
alwaysApply: true
---

@../../.ai-rules/generated.md
@../../.ai-rules/project.md
"""


def render_cursor(existing: str | None) -> str:
    if existing is not None and _OWNER not in existing:
        raise ConfigurationError("Cursor engineering.mdc exists but is not owned by airules")
    return _CONTENT
